#pragma once

#include "defhelper.hpp"

CONFIG(TILE_SIZE, 32);
CONFIG(VTREG_SIZE, 384);
CONFIG(PTREG_SIZE, 512);
CONFIG(PACC_NUM, 8);
CONFIG(PTEMP_NUM, 8);
CONFIG(PMASK_NUM, 6);
CONFIG(SIMD_LANE_SIZE, 8);

CONFIG(GEMM_LANE_SIZE, 4);
CONFIG(GEMM_LAST_LEVEL_LATENCY, 8);
CONFIG(GEMM_OUTPUT_LATENCY, 8);

CONFIG(LSU_BUS_BANKS, 8);
CONFIG(LSU_LOAD_SLOTS, 4);
CONFIG(LSU_MAX_LOAD_OUTSTANDING, LSU_LOAD_SLOTS * TILE_SIZE * 4);
CONFIG(LSU_BANK_QUEUE_DEPTH, LSU_MAX_LOAD_OUTSTANDING + TILE_SIZE * 4);

CONFIG(VTR_WID, clog2(VTREG_SIZE));
CONFIG(PTR_WID, clog2(PTREG_SIZE));

CONFIG(PACC_WID, clog2(PACC_NUM));
CONFIG(PTEMP_WID, clog2(PTEMP_NUM));
CONFIG(PMASK_WID, clog2(PMASK_NUM));
