#pragma once

#include "config.hpp"

ALIAS_ARRAY1(TileRow, uint8_t, TILE_SIZE);
ALIAS_ARRAY1(TileSIMDRow, uint8_t, SIMD_LANE_SIZE);

ALIAS_ARRAY1(Tile, TileRow, TILE_SIZE);
ALIAS_ARRAY1(TileSIMD, TileSIMDRow, TILE_SIZE);

ALIAS_ARRAY1(Tile32Row, uint32_t, TILE_SIZE);
ALIAS_ARRAY1(Tile32SIMDRow, uint32_t, SIMD_LANE_SIZE);

ALIAS_ARRAY1(Tile32, Tile32Row, TILE_SIZE);
ALIAS_ARRAY1(Tile32SIMD, Tile32SIMDRow, TILE_SIZE);

ALIAS_ARRAY1(TileMask, Int<TILE_SIZE>, TILE_SIZE);
