#pragma once

#include "defhelper.hpp"

CONFIG(TILE_SIZE, 32);
CONFIG(PACC_NUM, 8);
CONFIG(SIMD_LANE_SIZE, 8);

CONFIG(GEMM_LANE_SIZE, 4);
CONFIG(GEMM_LAST_LEVEL_LATENCY, 8);
CONFIG(GEMM_OUTPUT_LATENCY, 8);

ALIAS_ARRAY1(TileRow, uint8_t, TILE_SIZE);
ALIAS_ARRAY1(TileSIMDRow, uint8_t, SIMD_LANE_SIZE);

ALIAS_ARRAY1(Tile, TileRow, TILE_SIZE);
ALIAS_ARRAY1(TileSIMD, TileSIMDRow, TILE_SIZE);

ALIAS_ARRAY1(Tile32Row, uint32_t, TILE_SIZE);
ALIAS_ARRAY1(Tile32SIMDRow, uint32_t, SIMD_LANE_SIZE);

ALIAS_ARRAY1(Tile32, Tile32Row, TILE_SIZE);
ALIAS_ARRAY1(Tile32SIMD, Tile32SIMDRow, TILE_SIZE);

ENUM(DType) {
    DTYPE_SINT8 = 0x00,
    DTYPE_UINT8 = 0x01,
    DTYPE_F8E4M3 = 0x02,
    DTYPE_F8E5M2 = 0x03,
    DTYPE_SINT16 = 0x10,
    DTYPE_UINT16 = 0x11,
    DTYPE_F16 = 0x12,
    DTYPE_SINT32 = 0x20,
    DTYPE_UINT32 = 0x21,
    DTYPE_F32 = 0x22
};

